version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install -g serverless
      - npm install

  build:
    commands:
      - echo "Empaquetando la aplicación..."
      - serverless package

  post_build:
    commands:
      - echo "Desplegando la aplicación a AWS Lambda..."
      - serverless deploy

artifacts:
  files:
    - .serverless/**
